version: '3.8'

services:
  currency-exchange-dev:
    build: .
    ports:
      - "${PORT:-5001}:5001"
    env_file:
      - .env.development
    volumes:
      - .:/app
      - ./data:/app/data
    restart: unless-stopped
    environment:
      - DATABASE_URL=sqlite:///data/currency_exchange.db
      - FLASK_ENV=development
    command: ["python", "app.py"]